# Generated by Django 6.0.5 on 2026-05-26 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('class_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('compatible', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='app_brand_slug_fe70cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='app_categor_slug_d6a16b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('sub', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='app_contact_email_a74e4f_idx'), models.Index(fields=['created_at', 'is_active'], name='app_contact_created_3d0104_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrivacyTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('privacy_or_terms', models.CharField(choices=[('privacy', 'Privacy'), ('terms', 'Terms')], db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['privacy_or_terms', 'is_active'], name='app_privacy_privacy_435ee2_idx'), models.Index(fields=['created_at', 'is_active'], name='app_privacy_created_253b9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('favicon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_favicon', to='app.image')),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logo', to='app.image')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('main_model', models.CharField(db_index=True, max_length=100, unique=True)),
                ('compatible_model', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combo_brands', to='app.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combo_categories', to='app.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['main_model'], name='app_combo_main_mo_eaa1f0_idx'), models.Index(fields=['brand', 'category'], name='app_combo_brand_i_ba1710_idx'), models.Index(fields=['brand', 'is_active'], name='app_combo_brand_i_81010e_idx'), models.Index(fields=['category', 'is_active'], name='app_combo_categor_c83d6e_idx'), models.Index(fields=['created_at', 'is_active'], name='app_combo_created_4d3477_idx')],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_images', to='app.image')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='app_blog_slug_86e095_idx'), models.Index(fields=['created_at', 'is_active'], name='app_blog_created_baffef_idx')],
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('about', models.CharField(choices=[('story', 'Story'), ('vision', 'Vision'), ('mission', 'Mission')], db_index=True, max_length=100)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abouts', to='app.image')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['about', 'is_active'], name='app_about_about_8d833b_idx'), models.Index(fields=['created_at', 'is_active'], name='app_about_created_7044ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_icons', to='app.icon')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='app_nav_order_85d94c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('badge_label', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('page_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heroes', to='app.pagekey')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page_key', 'is_active'], name='app_hero_page_ke_2d3b05_idx'), models.Index(fields=['created_at', 'is_active'], name='app_hero_created_d8a90c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('role', models.CharField(blank=True, db_index=True, max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_images', to='app.image')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role', 'is_active'], name='app_team_role_a3134f_idx'), models.Index(fields=['created_at', 'is_active'], name='app_team_created_b09553_idx')],
            },
        ),
    ]
