# Generated by Django 6.0.4 on 2026-04-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_at_user_groups_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_type',
            field=models.CharField(blank=True, choices=[('register', 'Register'), ('reset', 'Reset Password')], max_length=10, null=True),
        ),
    ]
